/**
 * @file convertors.h
 * @author kossadda (https://github.com/kossadda)
 * @brief
 * @version 1.0
 * @date 2024-02-15
 *
 * @copyright Copyright (c) 2024
 *
 */

#ifndef CONVERTORS_TEST_H_
#define CONVERTORS_TEST_H_

#include "./common_test.h"

Suite *s21_from_float_to_decimal_case_1(void);
Suite *s21_from_float_to_decimal_case_2(void);
Suite *s21_from_float_to_decimal_case_3(void);
Suite *s21_from_float_to_decimal_case_4(void);
Suite *s21_from_float_to_decimal_case_5(void);
Suite *s21_from_float_to_decimal_case_6(void);
Suite *s21_from_float_to_decimal_case_7(void);
Suite *s21_from_float_to_decimal_case_8(void);
Suite *s21_from_float_to_decimal_case_9(void);
Suite *s21_from_float_to_decimal_case_10(void);
Suite *s21_from_float_to_decimal_case_11(void);
Suite *s21_from_float_to_decimal_case_12(void);
Suite *s21_from_float_to_decimal_case_13(void);
Suite *s21_from_float_to_decimal_case_14(void);
Suite *s21_from_float_to_decimal_case_15(void);
Suite *s21_from_float_to_decimal_case_16(void);
Suite *s21_from_float_to_decimal_case_17(void);
Suite *s21_from_float_to_decimal_case_18(void);
Suite *s21_from_float_to_decimal_case_19(void);
Suite *s21_from_float_to_decimal_case_20(void);
Suite *s21_from_float_to_decimal_case_21(void);
Suite *s21_from_float_to_decimal_case_22(void);
Suite *s21_from_float_to_decimal_case_23(void);
Suite *s21_from_float_to_decimal_case_24(void);
Suite *s21_from_float_to_decimal_case_25(void);
Suite *s21_from_float_to_decimal_case_26(void);
Suite *s21_from_float_to_decimal_case_27(void);
Suite *s21_from_float_to_decimal_case_28(void);
Suite *s21_from_float_to_decimal_case_29(void);
Suite *s21_from_float_to_decimal_case_30(void);
Suite *s21_from_float_to_decimal_case_31(void);
Suite *s21_from_float_to_decimal_case_32(void);
Suite *s21_from_float_to_decimal_case_33(void);
Suite *s21_from_float_to_decimal_case_34(void);
Suite *s21_from_float_to_decimal_case_35(void);
Suite *s21_from_float_to_decimal_case_36(void);
Suite *s21_from_float_to_decimal_case_37(void);
Suite *s21_from_float_to_decimal_case_38(void);
Suite *s21_from_float_to_decimal_case_39(void);
Suite *s21_from_float_to_decimal_case_40(void);
Suite *s21_from_float_to_decimal_case_41(void);
Suite *s21_from_float_to_decimal_case_42(void);
Suite *s21_from_float_to_decimal_case_43(void);
Suite *s21_from_float_to_decimal_case_44(void);
Suite *s21_from_float_to_decimal_case_45(void);
Suite *s21_from_float_to_decimal_case_46(void);
Suite *s21_from_float_to_decimal_case_47(void);
Suite *s21_from_float_to_decimal_case_48(void);
Suite *s21_from_float_to_decimal_case_49(void);
Suite *s21_from_float_to_decimal_case_50(void);
Suite *s21_from_float_to_decimal_case_51(void);
Suite *s21_from_float_to_decimal_case_52(void);
Suite *s21_from_float_to_decimal_case_53(void);
Suite *s21_from_float_to_decimal_case_54(void);
Suite *s21_from_float_to_decimal_case_55(void);
Suite *s21_from_float_to_decimal_case_56(void);
Suite *s21_from_float_to_decimal_case_57(void);
Suite *s21_from_float_to_decimal_case_58(void);
Suite *s21_from_float_to_decimal_case_59(void);
Suite *s21_from_float_to_decimal_case_60(void);
Suite *s21_from_float_to_decimal_case_61(void);
Suite *s21_from_float_to_decimal_case_62(void);
Suite *s21_from_float_to_decimal_case_63(void);
Suite *s21_from_float_to_decimal_case_64(void);
Suite *s21_from_float_to_decimal_case_65(void);
Suite *s21_from_float_to_decimal_case_66(void);
Suite *s21_from_float_to_decimal_case_67(void);
Suite *s21_from_float_to_decimal_case_68(void);
Suite *s21_from_float_to_decimal_case_69(void);
Suite *s21_from_float_to_decimal_case_70(void);
Suite *s21_from_float_to_decimal_case_71(void);
Suite *s21_from_float_to_decimal_case_72(void);
Suite *s21_from_float_to_decimal_case_73(void);
Suite *s21_from_float_to_decimal_case_74(void);
Suite *s21_from_float_to_decimal_case_75(void);
Suite *s21_from_float_to_decimal_case_76(void);
Suite *s21_from_float_to_decimal_case_77(void);
Suite *s21_from_float_to_decimal_case_78(void);
Suite *s21_from_float_to_decimal_case_79(void);
Suite *s21_from_float_to_decimal_case_80(void);
Suite *s21_from_float_to_decimal_case_81(void);
Suite *s21_from_float_to_decimal_case_82(void);
Suite *s21_from_float_to_decimal_case_83(void);
Suite *s21_from_float_to_decimal_case_84(void);
Suite *s21_from_float_to_decimal_case_85(void);
Suite *s21_from_float_to_decimal_case_86(void);
Suite *s21_from_float_to_decimal_case_87(void);
Suite *s21_from_float_to_decimal_case_88(void);
Suite *s21_from_float_to_decimal_case_89(void);
Suite *s21_from_float_to_decimal_case_90(void);
Suite *s21_from_float_to_decimal_case_91(void);
Suite *s21_from_float_to_decimal_case_92(void);
Suite *s21_from_float_to_decimal_case_93(void);
Suite *s21_from_float_to_decimal_case_94(void);
Suite *s21_from_float_to_decimal_case_95(void);
Suite *s21_from_float_to_decimal_case_96(void);
Suite *s21_from_float_to_decimal_case_97(void);
Suite *s21_from_float_to_decimal_case_98(void);
Suite *s21_from_float_to_decimal_case_99(void);
Suite *s21_from_float_to_decimal_case_100(void);

// Suite *s21_from_int_to_decimal_case_1(void);
// Suite *s21_from_int_to_decimal_case_2(void);
// Suite *s21_from_int_to_decimal_case_3(void);
// Suite *s21_from_int_to_decimal_case_4(void);
// Suite *s21_from_int_to_decimal_case_5(void);
// Suite *s21_from_int_to_decimal_case_6(void);
// Suite *s21_from_int_to_decimal_case_7(void);
// Suite *s21_from_int_to_decimal_case_8(void);
// Suite *s21_from_int_to_decimal_case_9(void);
// Suite *s21_from_int_to_decimal_case_10(void);
// Suite *s21_from_int_to_decimal_case_11(void);
// Suite *s21_from_int_to_decimal_case_12(void);
// Suite *s21_from_int_to_decimal_case_13(void);
// Suite *s21_from_int_to_decimal_case_14(void);
// Suite *s21_from_int_to_decimal_case_15(void);
// Suite *s21_from_int_to_decimal_case_16(void);
// Suite *s21_from_int_to_decimal_case_17(void);
// Suite *s21_from_int_to_decimal_case_18(void);
// Suite *s21_from_int_to_decimal_case_19(void);
// Suite *s21_from_int_to_decimal_case_20(void);
// Suite *s21_from_int_to_decimal_case_21(void);
// Suite *s21_from_int_to_decimal_case_22(void);
// Suite *s21_from_int_to_decimal_case_23(void);
// Suite *s21_from_int_to_decimal_case_24(void);
// Suite *s21_from_int_to_decimal_case_25(void);
// Suite *s21_from_int_to_decimal_case_26(void);
// Suite *s21_from_int_to_decimal_case_27(void);
// Suite *s21_from_int_to_decimal_case_28(void);
// Suite *s21_from_int_to_decimal_case_29(void);
// Suite *s21_from_int_to_decimal_case_30(void);
// Suite *s21_from_int_to_decimal_case_31(void);
// Suite *s21_from_int_to_decimal_case_32(void);
// Suite *s21_from_int_to_decimal_case_33(void);
// Suite *s21_from_int_to_decimal_case_34(void);
// Suite *s21_from_int_to_decimal_case_35(void);
// Suite *s21_from_int_to_decimal_case_36(void);
// Suite *s21_from_int_to_decimal_case_37(void);
// Suite *s21_from_int_to_decimal_case_38(void);
// Suite *s21_from_int_to_decimal_case_39(void);
// Suite *s21_from_int_to_decimal_case_40(void);
// Suite *s21_from_int_to_decimal_case_41(void);
// Suite *s21_from_int_to_decimal_case_42(void);
// Suite *s21_from_int_to_decimal_case_43(void);
// Suite *s21_from_int_to_decimal_case_44(void);
// Suite *s21_from_int_to_decimal_case_45(void);
// Suite *s21_from_int_to_decimal_case_46(void);
// Suite *s21_from_int_to_decimal_case_47(void);
// Suite *s21_from_int_to_decimal_case_48(void);
// Suite *s21_from_int_to_decimal_case_49(void);
// Suite *s21_from_int_to_decimal_case_50(void);
// Suite *s21_from_int_to_decimal_case_51(void);
// Suite *s21_from_int_to_decimal_case_52(void);
// Suite *s21_from_int_to_decimal_case_53(void);
// Suite *s21_from_int_to_decimal_case_54(void);
// Suite *s21_from_int_to_decimal_case_55(void);
// Suite *s21_from_int_to_decimal_case_56(void);
// Suite *s21_from_int_to_decimal_case_57(void);
// Suite *s21_from_int_to_decimal_case_58(void);
// Suite *s21_from_int_to_decimal_case_59(void);
// Suite *s21_from_int_to_decimal_case_60(void);
// Suite *s21_from_int_to_decimal_case_61(void);
// Suite *s21_from_int_to_decimal_case_62(void);
// Suite *s21_from_int_to_decimal_case_63(void);
// Suite *s21_from_int_to_decimal_case_64(void);
// Suite *s21_from_int_to_decimal_case_65(void);
// Suite *s21_from_int_to_decimal_case_66(void);
// Suite *s21_from_int_to_decimal_case_67(void);
// Suite *s21_from_int_to_decimal_case_68(void);
// Suite *s21_from_int_to_decimal_case_69(void);
// Suite *s21_from_int_to_decimal_case_70(void);
// Suite *s21_from_int_to_decimal_case_71(void);
// Suite *s21_from_int_to_decimal_case_72(void);
// Suite *s21_from_int_to_decimal_case_73(void);
// Suite *s21_from_int_to_decimal_case_74(void);
// Suite *s21_from_int_to_decimal_case_75(void);
// Suite *s21_from_int_to_decimal_case_76(void);
// Suite *s21_from_int_to_decimal_case_77(void);
// Suite *s21_from_int_to_decimal_case_78(void);
// Suite *s21_from_int_to_decimal_case_79(void);
// Suite *s21_from_int_to_decimal_case_80(void);
// Suite *s21_from_int_to_decimal_case_81(void);
// Suite *s21_from_int_to_decimal_case_82(void);
// Suite *s21_from_int_to_decimal_case_83(void);
// Suite *s21_from_int_to_decimal_case_84(void);
// Suite *s21_from_int_to_decimal_case_85(void);
// Suite *s21_from_int_to_decimal_case_86(void);
// Suite *s21_from_int_to_decimal_case_87(void);
// Suite *s21_from_int_to_decimal_case_88(void);
// Suite *s21_from_int_to_decimal_case_89(void);
// Suite *s21_from_int_to_decimal_case_90(void);
// Suite *s21_from_int_to_decimal_case_91(void);
// Suite *s21_from_int_to_decimal_case_92(void);
// Suite *s21_from_int_to_decimal_case_93(void);
// Suite *s21_from_int_to_decimal_case_94(void);
// Suite *s21_from_int_to_decimal_case_95(void);
// Suite *s21_from_int_to_decimal_case_96(void);
// Suite *s21_from_int_to_decimal_case_97(void);
// Suite *s21_from_int_to_decimal_case_98(void);
// Suite *s21_from_int_to_decimal_case_99(void);
// Suite *s21_from_int_to_decimal_case_100(void);

// Suite *s21_from_decimal_to_int_case_1(void);
// Suite *s21_from_decimal_to_int_case_2(void);
// Suite *s21_from_decimal_to_int_case_3(void);
// Suite *s21_from_decimal_to_int_case_4(void);
// Suite *s21_from_decimal_to_int_case_5(void);
// Suite *s21_from_decimal_to_int_case_6(void);
// Suite *s21_from_decimal_to_int_case_7(void);
// Suite *s21_from_decimal_to_int_case_8(void);
// Suite *s21_from_decimal_to_int_case_9(void);
// Suite *s21_from_decimal_to_int_case_10(void);
// Suite *s21_from_decimal_to_int_case_11(void);
// Suite *s21_from_decimal_to_int_case_12(void);
// Suite *s21_from_decimal_to_int_case_13(void);
// Suite *s21_from_decimal_to_int_case_14(void);
// Suite *s21_from_decimal_to_int_case_15(void);
// Suite *s21_from_decimal_to_int_case_16(void);
// Suite *s21_from_decimal_to_int_case_17(void);
// Suite *s21_from_decimal_to_int_case_18(void);
// Suite *s21_from_decimal_to_int_case_19(void);
// Suite *s21_from_decimal_to_int_case_20(void);
// Suite *s21_from_decimal_to_int_case_21(void);
// Suite *s21_from_decimal_to_int_case_22(void);
// Suite *s21_from_decimal_to_int_case_23(void);
// Suite *s21_from_decimal_to_int_case_24(void);
// Suite *s21_from_decimal_to_int_case_25(void);
// Suite *s21_from_decimal_to_int_case_26(void);
// Suite *s21_from_decimal_to_int_case_27(void);
// Suite *s21_from_decimal_to_int_case_28(void);
// Suite *s21_from_decimal_to_int_case_29(void);
// Suite *s21_from_decimal_to_int_case_30(void);
// Suite *s21_from_decimal_to_int_case_31(void);
// Suite *s21_from_decimal_to_int_case_32(void);
// Suite *s21_from_decimal_to_int_case_33(void);
// Suite *s21_from_decimal_to_int_case_34(void);
// Suite *s21_from_decimal_to_int_case_35(void);
// Suite *s21_from_decimal_to_int_case_36(void);
// Suite *s21_from_decimal_to_int_case_37(void);
// Suite *s21_from_decimal_to_int_case_38(void);
// Suite *s21_from_decimal_to_int_case_39(void);
// Suite *s21_from_decimal_to_int_case_40(void);
// Suite *s21_from_decimal_to_int_case_41(void);
// Suite *s21_from_decimal_to_int_case_42(void);
// Suite *s21_from_decimal_to_int_case_43(void);
// Suite *s21_from_decimal_to_int_case_44(void);
// Suite *s21_from_decimal_to_int_case_45(void);
// Suite *s21_from_decimal_to_int_case_46(void);
// Suite *s21_from_decimal_to_int_case_47(void);
// Suite *s21_from_decimal_to_int_case_48(void);
// Suite *s21_from_decimal_to_int_case_49(void);
// Suite *s21_from_decimal_to_int_case_50(void);
// Suite *s21_from_decimal_to_int_case_51(void);
// Suite *s21_from_decimal_to_int_case_52(void);
// Suite *s21_from_decimal_to_int_case_53(void);
// Suite *s21_from_decimal_to_int_case_54(void);
// Suite *s21_from_decimal_to_int_case_55(void);
// Suite *s21_from_decimal_to_int_case_56(void);
// Suite *s21_from_decimal_to_int_case_57(void);
// Suite *s21_from_decimal_to_int_case_58(void);
// Suite *s21_from_decimal_to_int_case_59(void);
// Suite *s21_from_decimal_to_int_case_60(void);
// Suite *s21_from_decimal_to_int_case_61(void);
// Suite *s21_from_decimal_to_int_case_62(void);
// Suite *s21_from_decimal_to_int_case_63(void);
// Suite *s21_from_decimal_to_int_case_64(void);
// Suite *s21_from_decimal_to_int_case_65(void);
// Suite *s21_from_decimal_to_int_case_66(void);
// Suite *s21_from_decimal_to_int_case_67(void);
// Suite *s21_from_decimal_to_int_case_68(void);
// Suite *s21_from_decimal_to_int_case_69(void);
// Suite *s21_from_decimal_to_int_case_70(void);
// Suite *s21_from_decimal_to_int_case_71(void);
// Suite *s21_from_decimal_to_int_case_72(void);
// Suite *s21_from_decimal_to_int_case_73(void);
// Suite *s21_from_decimal_to_int_case_74(void);
// Suite *s21_from_decimal_to_int_case_75(void);
// Suite *s21_from_decimal_to_int_case_76(void);
// Suite *s21_from_decimal_to_int_case_77(void);
// Suite *s21_from_decimal_to_int_case_78(void);
// Suite *s21_from_decimal_to_int_case_79(void);
// Suite *s21_from_decimal_to_int_case_80(void);
// Suite *s21_from_decimal_to_int_case_81(void);
// Suite *s21_from_decimal_to_int_case_82(void);
// Suite *s21_from_decimal_to_int_case_83(void);
// Suite *s21_from_decimal_to_int_case_84(void);
// Suite *s21_from_decimal_to_int_case_85(void);
// Suite *s21_from_decimal_to_int_case_86(void);
// Suite *s21_from_decimal_to_int_case_87(void);
// Suite *s21_from_decimal_to_int_case_88(void);
// Suite *s21_from_decimal_to_int_case_89(void);
// Suite *s21_from_decimal_to_int_case_90(void);
// Suite *s21_from_decimal_to_int_case_91(void);
// Suite *s21_from_decimal_to_int_case_92(void);
// Suite *s21_from_decimal_to_int_case_93(void);
// Suite *s21_from_decimal_to_int_case_94(void);
// Suite *s21_from_decimal_to_int_case_95(void);
// Suite *s21_from_decimal_to_int_case_96(void);
// Suite *s21_from_decimal_to_int_case_97(void);
// Suite *s21_from_decimal_to_int_case_98(void);
// Suite *s21_from_decimal_to_int_case_99(void);
// Suite *s21_from_decimal_to_int_case_100(void);

// Suite *s21_from_decimal_to_float_case_1(void);
// Suite *s21_from_decimal_to_float_case_2(void);
// Suite *s21_from_decimal_to_float_case_3(void);
// Suite *s21_from_decimal_to_float_case_4(void);
// Suite *s21_from_decimal_to_float_case_5(void);
// Suite *s21_from_decimal_to_float_case_6(void);
// Suite *s21_from_decimal_to_float_case_7(void);
// Suite *s21_from_decimal_to_float_case_8(void);
// Suite *s21_from_decimal_to_float_case_9(void);
// Suite *s21_from_decimal_to_float_case_10(void);
// Suite *s21_from_decimal_to_float_case_11(void);
// Suite *s21_from_decimal_to_float_case_12(void);
// Suite *s21_from_decimal_to_float_case_13(void);
// Suite *s21_from_decimal_to_float_case_14(void);
// Suite *s21_from_decimal_to_float_case_15(void);
// Suite *s21_from_decimal_to_float_case_16(void);
// Suite *s21_from_decimal_to_float_case_17(void);
// Suite *s21_from_decimal_to_float_case_18(void);
// Suite *s21_from_decimal_to_float_case_19(void);
// Suite *s21_from_decimal_to_float_case_20(void);
// Suite *s21_from_decimal_to_float_case_21(void);
// Suite *s21_from_decimal_to_float_case_22(void);
// Suite *s21_from_decimal_to_float_case_23(void);
// Suite *s21_from_decimal_to_float_case_24(void);
// Suite *s21_from_decimal_to_float_case_25(void);
// Suite *s21_from_decimal_to_float_case_26(void);
// Suite *s21_from_decimal_to_float_case_27(void);
// Suite *s21_from_decimal_to_float_case_28(void);
// Suite *s21_from_decimal_to_float_case_29(void);
// Suite *s21_from_decimal_to_float_case_30(void);
// Suite *s21_from_decimal_to_float_case_31(void);
// Suite *s21_from_decimal_to_float_case_32(void);
// Suite *s21_from_decimal_to_float_case_33(void);
// Suite *s21_from_decimal_to_float_case_34(void);
// Suite *s21_from_decimal_to_float_case_35(void);
// Suite *s21_from_decimal_to_float_case_36(void);
// Suite *s21_from_decimal_to_float_case_37(void);
// Suite *s21_from_decimal_to_float_case_38(void);
// Suite *s21_from_decimal_to_float_case_39(void);
// Suite *s21_from_decimal_to_float_case_40(void);
// Suite *s21_from_decimal_to_float_case_41(void);
// Suite *s21_from_decimal_to_float_case_42(void);
// Suite *s21_from_decimal_to_float_case_43(void);
// Suite *s21_from_decimal_to_float_case_44(void);
// Suite *s21_from_decimal_to_float_case_45(void);
// Suite *s21_from_decimal_to_float_case_46(void);
// Suite *s21_from_decimal_to_float_case_47(void);
// Suite *s21_from_decimal_to_float_case_48(void);
// Suite *s21_from_decimal_to_float_case_49(void);
// Suite *s21_from_decimal_to_float_case_50(void);
// Suite *s21_from_decimal_to_float_case_51(void);
// Suite *s21_from_decimal_to_float_case_52(void);
// Suite *s21_from_decimal_to_float_case_53(void);
// Suite *s21_from_decimal_to_float_case_54(void);
// Suite *s21_from_decimal_to_float_case_55(void);
// Suite *s21_from_decimal_to_float_case_56(void);
// Suite *s21_from_decimal_to_float_case_57(void);
// Suite *s21_from_decimal_to_float_case_58(void);
// Suite *s21_from_decimal_to_float_case_59(void);
// Suite *s21_from_decimal_to_float_case_60(void);
// Suite *s21_from_decimal_to_float_case_61(void);
// Suite *s21_from_decimal_to_float_case_62(void);
// Suite *s21_from_decimal_to_float_case_63(void);
// Suite *s21_from_decimal_to_float_case_64(void);
// Suite *s21_from_decimal_to_float_case_65(void);
// Suite *s21_from_decimal_to_float_case_66(void);
// Suite *s21_from_decimal_to_float_case_67(void);
// Suite *s21_from_decimal_to_float_case_68(void);
// Suite *s21_from_decimal_to_float_case_69(void);
// Suite *s21_from_decimal_to_float_case_70(void);
// Suite *s21_from_decimal_to_float_case_71(void);
// Suite *s21_from_decimal_to_float_case_72(void);
// Suite *s21_from_decimal_to_float_case_73(void);
// Suite *s21_from_decimal_to_float_case_74(void);
// Suite *s21_from_decimal_to_float_case_75(void);
// Suite *s21_from_decimal_to_float_case_76(void);
// Suite *s21_from_decimal_to_float_case_77(void);
// Suite *s21_from_decimal_to_float_case_78(void);
// Suite *s21_from_decimal_to_float_case_79(void);
// Suite *s21_from_decimal_to_float_case_80(void);
// Suite *s21_from_decimal_to_float_case_81(void);
// Suite *s21_from_decimal_to_float_case_82(void);
// Suite *s21_from_decimal_to_float_case_83(void);
// Suite *s21_from_decimal_to_float_case_84(void);
// Suite *s21_from_decimal_to_float_case_85(void);
// Suite *s21_from_decimal_to_float_case_86(void);
// Suite *s21_from_decimal_to_float_case_87(void);
// Suite *s21_from_decimal_to_float_case_88(void);
// Suite *s21_from_decimal_to_float_case_89(void);
// Suite *s21_from_decimal_to_float_case_90(void);
// Suite *s21_from_decimal_to_float_case_91(void);
// Suite *s21_from_decimal_to_float_case_92(void);
// Suite *s21_from_decimal_to_float_case_93(void);
// Suite *s21_from_decimal_to_float_case_94(void);
// Suite *s21_from_decimal_to_float_case_95(void);
// Suite *s21_from_decimal_to_float_case_96(void);
// Suite *s21_from_decimal_to_float_case_97(void);
// Suite *s21_from_decimal_to_float_case_98(void);
// Suite *s21_from_decimal_to_float_case_99(void);
// Suite *s21_from_decimal_to_float_case_100(void);

#endif  // CONVERTORS_TEST_H_
