name: Tests
on:
  push:

jobs:
  clang:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: sudo apt-get install clang-format -y
      - name: clang-format
        run: make clang_check
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: make s21_decimal.a
  